############################################################
#
#  Device Trackers
#
############################################################

- platform: owntracks
  track_new_devices: no
  waypoints: True
