############################################################
#
# Media Players
#
############################################################

- platform: kodi
  name: 'Living Room Kodi'
  host: 192.168.1.27

- platform: samsungtv
  name: 'Living Room TV'
  host: 192.168.1.26

- platform: samsungtv
  name: 'Bedroom TV'
  host: 192.168.1.28

- platform: plex
