############################################################
#
# MQTT Binary Sensors
#
############################################################

- platform: mqtt
  name: "Bedroom Motion"
  state_topic: "bedroom_pi/motion"
  sensor_class: motion

- platform: mqtt
  name: "Back Yard Motion"
  state_topic: "back_yard_pi/motion"
  sensor_class: motion
  
- platform: mqtt
  name: "Kitchen Motion"
  state_topic: "kitchen_pi/motion"
  sensor_class: motion
