############################################################
#
# Automations View
#
############################################################

automation_view:
  view: yes
  entities:
    - group.automation_view_general_automations
    - group.automation_view_notification_automations

automation_view_general_automations:
  name: "General Automations"
  control: hidden
  entities:
    - automation.heal_zwave_nightly
    - automation.trigger_alarm_while_armed_away

automation_view_notification_automations:
  name: "Notification Automations"
  control: hidden
  entities:
    - automation.notify_when_front_door_is_locked
    - automation.notify_when_front_door_is_unlocked
    - automation.send_snapshot_when_doorbell_rings
    - automation.preview_camera_on_kodi_when_doorbell_rings
    - automation.notify_kodi_when_doorbell_rings

