############################################################
#
# Darksky Sensor
#
############################################################

- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - temperature
    - humidity
    - minutely_summary
    - temperature_max
    - temperature_min
    - precip_probability
    - precip_intensity
    - wind_speed
    - pressure
    - wind_bearing
    - apparent_temperature
    - icon
    - cloud_cover
